name: SonarCloud
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
            dotnet-version: 6.0.x

      - name: Install dependencies
        run:  dotnet restore

      - name: Build
        run:  dotnet build
             
      - name: Test
        run:  dotnet test --no-build --logger:trx  --verbosity normal

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
           trx_files: "TestResults/*.trx"


